# Generated by Django 3.1.2 on 2020-11-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EpicPro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='juegos'),
        ),
    ]
